// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file implements the knownFormats map which records the valid
// formats for a given type. The valid formats must correspond to
// supported compiler formats implemented in fmt.go, or whatever
// other format verbs are implemented for the given type. The map may
// also be used to change the use of a format verb across all compiler
// sources automatically (for instance, if the implementation of fmt.go
// changes), by using the -r option together with the new formats in the
// map. To generate this file automatically from the existing source,
// run: go test -run Formats -u.
//
// See the package comment in fmt_test.go for additional information.

package main_test

// knownFormats entries are of the form "typename format" -> "newformat".
// An absent entry means that the format is not recognized as valid.
// An empty new format means that the format should remain unchanged.
var knownFormats = map[string]string{
	"*bytes.Buffer %s": "",
	"*github.com/pgavlin/gc/compile/gc.EscLocation %v":         "",
	"*github.com/pgavlin/gc/compile/gc.Mpflt %v":               "",
	"*github.com/pgavlin/gc/compile/gc.Mpint %v":               "",
	"*github.com/pgavlin/gc/compile/gc.Node %#v":               "",
	"*github.com/pgavlin/gc/compile/gc.Node %+S":               "",
	"*github.com/pgavlin/gc/compile/gc.Node %+v":               "",
	"*github.com/pgavlin/gc/compile/gc.Node %L":                "",
	"*github.com/pgavlin/gc/compile/gc.Node %S":                "",
	"*github.com/pgavlin/gc/compile/gc.Node %j":                "",
	"*github.com/pgavlin/gc/compile/gc.Node %p":                "",
	"*github.com/pgavlin/gc/compile/gc.Node %v":                "",
	"*github.com/pgavlin/gc/compile/ssa.Block %s":              "",
	"*github.com/pgavlin/gc/compile/ssa.Block %v":              "",
	"*github.com/pgavlin/gc/compile/ssa.Func %s":               "",
	"*github.com/pgavlin/gc/compile/ssa.Func %v":               "",
	"*github.com/pgavlin/gc/compile/ssa.Register %s":           "",
	"*github.com/pgavlin/gc/compile/ssa.Register %v":           "",
	"*github.com/pgavlin/gc/compile/ssa.SparseTreeNode %v":     "",
	"*github.com/pgavlin/gc/compile/ssa.Value %s":              "",
	"*github.com/pgavlin/gc/compile/ssa.Value %v":              "",
	"*github.com/pgavlin/gc/compile/ssa.sparseTreeMapEntry %v": "",
	"*github.com/pgavlin/gc/compile/types.Field %p":            "",
	"*github.com/pgavlin/gc/compile/types.Field %v":            "",
	"*github.com/pgavlin/gc/compile/types.Sym %0S":             "",
	"*github.com/pgavlin/gc/compile/types.Sym %S":              "",
	"*github.com/pgavlin/gc/compile/types.Sym %p":              "",
	"*github.com/pgavlin/gc/compile/types.Sym %v":              "",
	"*github.com/pgavlin/gc/compile/types.Type %#L":            "",
	"*github.com/pgavlin/gc/compile/types.Type %#v":            "",
	"*github.com/pgavlin/gc/compile/types.Type %+v":            "",
	"*github.com/pgavlin/gc/compile/types.Type %-S":            "",
	"*github.com/pgavlin/gc/compile/types.Type %0S":            "",
	"*github.com/pgavlin/gc/compile/types.Type %L":             "",
	"*github.com/pgavlin/gc/compile/types.Type %S":             "",
	"*github.com/pgavlin/gc/compile/types.Type %p":             "",
	"*github.com/pgavlin/gc/compile/types.Type %s":             "",
	"*github.com/pgavlin/gc/compile/types.Type %v":             "",
	"*github.com/pgavlin/gc/obj.Addr %v":                       "",
	"*github.com/pgavlin/gc/obj.LSym %v":                       "",
	"*math/big.Float %f":                                       "",
	"*math/big.Int %#x":                                        "",
	"*math/big.Int %s":                                         "",
	"*math/big.Int %v":                                         "",
	"[16]byte %x":                                              "",
	"[]*github.com/pgavlin/gc/compile/ssa.Block %v":            "",
	"[]*github.com/pgavlin/gc/compile/ssa.Value %v":            "",
	"[][]string %q": "",
	"[]byte %s":     "",
	"[]byte %x":     "",
	"[]github.com/pgavlin/gc/compile/ssa.Edge %v":      "",
	"[]github.com/pgavlin/gc/compile/ssa.ID %v":        "",
	"[]github.com/pgavlin/gc/compile/ssa.posetNode %v": "",
	"[]github.com/pgavlin/gc/compile/ssa.posetUndo %v": "",
	"[]github.com/pgavlin/gc/compile/syntax.token %s":  "",
	"[]string %v": "",
	"[]uint32 %v": "",
	"bool %v":     "",
	"byte %08b":   "",
	"byte %c":     "",
	"byte %q":     "",
	"byte %v":     "",
	"github.com/pgavlin/gc/compile/arm.shift %d":            "",
	"github.com/pgavlin/gc/compile/gc.Class %d":             "",
	"github.com/pgavlin/gc/compile/gc.Class %s":             "",
	"github.com/pgavlin/gc/compile/gc.Class %v":             "",
	"github.com/pgavlin/gc/compile/gc.Ctype %d":             "",
	"github.com/pgavlin/gc/compile/gc.Ctype %v":             "",
	"github.com/pgavlin/gc/compile/gc.Nodes %#v":            "",
	"github.com/pgavlin/gc/compile/gc.Nodes %+v":            "",
	"github.com/pgavlin/gc/compile/gc.Nodes %.v":            "",
	"github.com/pgavlin/gc/compile/gc.Nodes %v":             "",
	"github.com/pgavlin/gc/compile/gc.Op %#v":               "",
	"github.com/pgavlin/gc/compile/gc.Op %v":                "",
	"github.com/pgavlin/gc/compile/gc.Val %#v":              "",
	"github.com/pgavlin/gc/compile/gc.Val %T":               "",
	"github.com/pgavlin/gc/compile/gc.Val %v":               "",
	"github.com/pgavlin/gc/compile/gc.fmtMode %d":           "",
	"github.com/pgavlin/gc/compile/gc.initKind %d":          "",
	"github.com/pgavlin/gc/compile/gc.itag %v":              "",
	"github.com/pgavlin/gc/compile/ssa.BranchPrediction %d": "",
	"github.com/pgavlin/gc/compile/ssa.Edge %v":             "",
	"github.com/pgavlin/gc/compile/ssa.GCNode %v":           "",
	"github.com/pgavlin/gc/compile/ssa.ID %d":               "",
	"github.com/pgavlin/gc/compile/ssa.ID %v":               "",
	"github.com/pgavlin/gc/compile/ssa.LocPair %s":          "",
	"github.com/pgavlin/gc/compile/ssa.LocalSlot %s":        "",
	"github.com/pgavlin/gc/compile/ssa.LocalSlot %v":        "",
	"github.com/pgavlin/gc/compile/ssa.Location %T":         "",
	"github.com/pgavlin/gc/compile/ssa.Location %s":         "",
	"github.com/pgavlin/gc/compile/ssa.Op %s":               "",
	"github.com/pgavlin/gc/compile/ssa.Op %v":               "",
	"github.com/pgavlin/gc/compile/ssa.Sym %v":              "",
	"github.com/pgavlin/gc/compile/ssa.ValAndOff %s":        "",
	"github.com/pgavlin/gc/compile/ssa.domain %v":           "",
	"github.com/pgavlin/gc/compile/ssa.flagConstant %s":     "",
	"github.com/pgavlin/gc/compile/ssa.posetNode %v":        "",
	"github.com/pgavlin/gc/compile/ssa.posetTestOp %v":      "",
	"github.com/pgavlin/gc/compile/ssa.rbrank %d":           "",
	"github.com/pgavlin/gc/compile/ssa.regMask %d":          "",
	"github.com/pgavlin/gc/compile/ssa.register %d":         "",
	"github.com/pgavlin/gc/compile/ssa.relation %s":         "",
	"github.com/pgavlin/gc/compile/syntax.Error %q":         "",
	"github.com/pgavlin/gc/compile/syntax.Expr %#v":         "",
	"github.com/pgavlin/gc/compile/syntax.LitKind %d":       "",
	"github.com/pgavlin/gc/compile/syntax.Node %T":          "",
	"github.com/pgavlin/gc/compile/syntax.Operator %s":      "",
	"github.com/pgavlin/gc/compile/syntax.Pos %s":           "",
	"github.com/pgavlin/gc/compile/syntax.Pos %v":           "",
	"github.com/pgavlin/gc/compile/syntax.position %s":      "",
	"github.com/pgavlin/gc/compile/syntax.token %q":         "",
	"github.com/pgavlin/gc/compile/syntax.token %s":         "",
	"github.com/pgavlin/gc/compile/types.EType %d":          "",
	"github.com/pgavlin/gc/compile/types.EType %s":          "",
	"github.com/pgavlin/gc/compile/types.EType %v":          "",
	"github.com/pgavlin/gc/obj.ABI %v":                      "",
	"error %v":                                              "",
	"float64 %.2f":                                          "",
	"float64 %.3f":                                          "",
	"float64 %.6g":                                          "",
	"float64 %g":                                            "",
	"int %#x":                                               "",
	"int %-12d":                                             "",
	"int %-6d":                                              "",
	"int %-8o":                                              "",
	"int %02d":                                              "",
	"int %6d":                                               "",
	"int %c":                                                "",
	"int %d":                                                "",
	"int %v":                                                "",
	"int %x":                                                "",
	"int16 %d":                                              "",
	"int16 %x":                                              "",
	"int32 %#x":                                             "",
	"int32 %d":                                              "",
	"int32 %v":                                              "",
	"int32 %x":                                              "",
	"int64 %#x":                                             "",
	"int64 %+d":                                             "",
	"int64 %-10d":                                           "",
	"int64 %.5d":                                            "",
	"int64 %d":                                              "",
	"int64 %v":                                              "",
	"int64 %x":                                              "",
	"int8 %d":                                               "",
	"int8 %v":                                               "",
	"int8 %x":                                               "",
	"interface{} %#v":                                       "",
	"interface{} %T":                                        "",
	"interface{} %p":                                        "",
	"interface{} %q":                                        "",
	"interface{} %s":                                        "",
	"interface{} %v":                                        "",
	"map[*github.com/pgavlin/gc/compile/gc.Node]*github.com/pgavlin/gc/compile/ssa.Value %v": "",
	"map[*github.com/pgavlin/gc/compile/gc.Node][]*github.com/pgavlin/gc/compile/gc.Node %v": "",
	"map[github.com/pgavlin/gc/compile/ssa.ID]uint32 %v":                                     "",
	"map[int64]uint32 %v":  "",
	"math/big.Accuracy %s": "",
	"reflect.Type %s":      "",
	"rune %#U":             "",
	"rune %c":              "",
	"rune %q":              "",
	"string %-*s":          "",
	"string %-16s":         "",
	"string %-6s":          "",
	"string %q":            "",
	"string %s":            "",
	"string %v":            "",
	"time.Duration %d":     "",
	"time.Duration %v":     "",
	"uint %04x":            "",
	"uint %5d":             "",
	"uint %d":              "",
	"uint %x":              "",
	"uint16 %d":            "",
	"uint16 %x":            "",
	"uint32 %#U":           "",
	"uint32 %#x":           "",
	"uint32 %d":            "",
	"uint32 %v":            "",
	"uint32 %x":            "",
	"uint64 %08x":          "",
	"uint64 %b":            "",
	"uint64 %d":            "",
	"uint64 %x":            "",
	"uint8 %#x":            "",
	"uint8 %d":             "",
	"uint8 %v":             "",
	"uint8 %x":             "",
	"uintptr %d":           "",
}
